- include: ../../scaleio-common/tasks/install_scaleio.yml

- name: login with new password
  command: scli --login --username admin --password "{{ scaleio_password }}"
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"

- name: add primary tie breaker
  command: scli --add_standby_mdm --new_mdm_ip "{{ scaleio_tb_primary_ip }}"  --mdm_role tb
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  register: add_primary_tb
  changed_when: ('single mode' not in add_primary_tb.stderr) or (add_primary_tb.rc == 0)
  failed_when: add_primary_tb.rc == 1

- name: add secondary tie breaker
  command: scli --add_standby_mdm --new_mdm_ip "{{ scaleio_tb_secondary_ip }}"  --mdm_role tb
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  register: add_secondary_tb
  changed_when: ('single mode' not in add_secondary_tb.stderr) or (add_secondary_tb.rc == 0)
  failed_when: add_secondary_tb.rc == 1
  when: scaleio_tb_secondary_ip is defined

- name: switch to cluster three node
  command: scli --switch_cluster_mode --cluster_mode "{{ scaleio_cluster_mode }}" --add_slave_mdm_ip  "{{ scaleio_mdm_secondary_ip }}" --add_tb_ip "{{ scaleio_tb_primary_ip }}"
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  when: ("'single mode' not in add_tb.stderr") and  ( scaleio_cluster_mode  == "3_node")

- name: switch to cluster five node
  command: scli --switch_cluster_mode --cluster_mode "{{ scaleio_cluster_mode }}" --add_slave_mdm_ip  "{{ scaleio_mdm_secondary_ip }}","{{ scaleio_mdm_tertiary_ip }}" --add_tb_ip "{{ scaleio_tb_primary_ip }}","{{ scaleio_tb_secondary_ip }}"
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  when: ("'single mode' not in add_tb.stderr") and ( scaleio_cluster_mode == "5_node")

- name: create the protection domain
  command: scli --add_protection_domain --mdm_ip "{{ scaleio_mdm_primary_ip }}" --protection_domain_name {{ scaleio_protection_domain }}
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  register: add_pd
  changed_when: "'already exists' not in add_pd.stderr"

- name: add fault set
  command: scli --add_fault_set --protection_domain_name "{{ scaleio_protection_domain }}" --fault_set_name "{{ item }}"
  with_items: "{{ scaleio_fault_set }}"
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  register: add_fs


- name: add storage pool
  command: scli --mdm_ip {{ scaleio_mdm_ips }} --add_storage_pool --protection_domain_name {{ scaleio_protection_domain }} --storage_pool_name {{ scaleio_storage_pool }}
  run_once: true
  register: storage_pool_add
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  changed_when: (storage_pool_add.rc == 7) or (storage_pool_add.rc == 0)
