- include: ../../scaleio-common/tasks/install_scaleio.yml

- name: install multiple sds if required (scaleio_sds_number > 1)
  include: install_scaleio_sds_{{ item }}.yml
  when: scaleio_sds_number > 1
  with_sequence: start="1" end="{{ scaleio_sds_number }}"

- name: find disks
  disk_facts:
  register: disks

- name: use local disk variable
  when: scaleio_sds_disks
  set_fact: disks="{{ scaleio_sds_disks }}"

- name: login to mdm
  command: scli --login --mdm_ip {{ scaleio_mdm_ips }} --username admin --password "{{ scaleio_password }}" --approve_certificate
  run_once: true
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"

- name: add sds without fault set
  command: scli --add_sds --mdm_ip {{ scaleio_mdm_ips }} --sds_ip {{ hostvars[inventory_hostname]['ansible_'+scaleio_interface]['ipv4']['address'] }} --storage_pool_name {{ scaleio_storage_pool }} --device_path {{ disks.ansible_available_disks|join(',') }} --sds_name "{{ inventory_hostname}}" --protection_domain_name {{ scaleio_protection_domain }}
  register: add_sds
  changed_when: ('already in use' in add_sds.stderr) or (add_sds.rc == 0)
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  ignore_errors: yes
  when: scaleio_fault_sets not defined

- name: add sds with fault set
  command: scli --add_sds --mdm_ip {{ scaleio_mdm_ips }} --sds_ip {{ hostvars[inventory_hostname]['ansible_'+scaleio_interface]['ipv4']['address'] }} --storage_pool_name {{ scaleio_storage_pool }} --device_path {{ disks.ansible_available_disks|join(',') }} --sds_name "{{ inventory_hostname}}" --protection_domain_name {{ scaleio_protection_domain }} --fault_set_name {{ item.fs }}
  register: add_sds
  changed_when: ('already in use' in add_sds.stderr) or (add_sds.rc == 0)
  delegate_to: "{{ scaleio_mdm_primary_hostname }}"
  ignore_errors: yes
  when: scaleio_fault_sets is defined and "{{ item.sds }}" == "{{ inventory_hostname }}"
  with_items: scaleio_fault_sets
